target/riscv: Fix Xqccmi ILUT execution
Signed-off-by: Brian Cain <brian.cain@oss.qualcomm.com>

diff --git a/tests/tcg/riscv32/Makefile.target b/tests/tcg/riscv32/Makefile.target
--- a/tests/tcg/riscv32/Makefile.target
+++ b/tests/tcg/riscv32/Makefile.target
@@ -213,6 +213,11 @@ build-xqccmi-asm-tests:
 		$(XQCCMI_INST_DIR)/qc.cm.ilut-illegal.S \
 		-o $(XQCCMI_OUT_ASM_DIR)/qc.cm.ilut-illegal-rv32
 	chmod +x $(XQCCMI_OUT_ASM_DIR)/qc.cm.ilut-illegal-rv32
+	$(CC_XQCCMI) --target=riscv32-unknown-linux-gnu -march=rv32imc \
+		-fuse-ld=lld -nostdlib -static -x assembler-with-cpp \
+		$(XQCCMI_INST_DIR)/qc.cm.ilut-restart.S \
+		-o $(XQCCMI_OUT_ASM_DIR)/qc.cm.ilut-restart-rv32
+	chmod +x $(XQCCMI_OUT_ASM_DIR)/qc.cm.ilut-restart-rv32
 
 .PHONY: run-xqccmi-asm-tests
 run-xqccmi-asm-tests: $(XQCCMI_OUT_ASM_DIR)/qc.cm.ilut-rv32
@@ -225,6 +230,14 @@ run-xqccmi-asm-tests: $(XQCCMI_OUT_ASM_DIR)/qc.cm.ilut-rv32
 		echo "FAIL ($${err}) $$exe"; \
 	fi
 	@exe=$(XQCCMI_OUT_ASM_DIR)/qc.cm.ilut-illegal-rv32; \
+	out=$$(timeout 5s $(QEMU) -cpu qc_iu $$exe); \
+	err=$$?; \
+	if [ $$err -eq 0 ]; then \
+		echo "PASS $$exe"; \
+	else \
+		echo "FAIL ($${err}) $$exe: $$out"; \
+	fi
+	@exe=$(XQCCMI_OUT_ASM_DIR)/qc.cm.ilut-restart-rv32; \
 	out=$$(timeout 5s $(QEMU) -cpu qc_iu $$exe); \
 	err=$$?; \
 	if [ $$err -eq 0 ]; then \
